name: vs_env_new
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bottleneck=1.3.4
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cudatoolkit=11.8.0
  - fftw=3.3.10
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - nomkl=1.0
  - numexpr=2.8.0
  - numpy=1.22.3
  - ocl-icd=2.3.1
  - ocl-icd-system=1.0.0
  - openmm=7.7.0
  - openssl=3.0.16
  - pip=25.0
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - readline=8.2
  - setuptools=75.8.0
  - six=1.17.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.2.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - altair==5.5.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - chex==0.1.89
      - clara==1.4.0
      - click==8.1.8
      - cloudpickle==3.1.1
      - contourpy==1.3.1
      - cuda-bindings==12.8.0
      - cuda-python==12.8.0
      - cudf-cu12==25.2.2
      - cuml-cu12==25.2.1
      - cupy-cuda12x==13.4.1
      - cuvs-cu12==25.2.1
      - cycler==0.12.1
      - dask==2024.12.1
      - dask-cuda==25.2.0
      - dask-cudf-cu12==25.2.2
      - dask-expr==1.1.21
      - datamol==0.12.5
      - deepchem==2.8.0
      - dgl==2.1.0
      - distributed==2024.12.1
      - distributed-ucxx-cu12==0.42.0
      - dm-haiku==0.0.13
      - etils==1.12.2
      - faiss-gpu==1.7.2
      - fastrlock==0.8.3
      - filelock==3.18.0
      - flask==3.1.0
      - flatbuffers==25.2.10
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2025.3.2
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-pasta==0.2.0
      - grpcio==1.71.0
      - h5py==3.13.0
      - hdbscan==0.8.40
      - huggingface-hub==0.30.2
      - idna==3.10
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - itsdangerous==2.2.0
      - jax==0.5.3
      - jaxlib==0.5.3
      - jinja2==3.1.6
      - jmp==0.0.4
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - keras==3.9.2
      - kiwisolver==1.4.8
      - lark-parser==0.12.0
      - levenshtein==0.27.1
      - libclang==18.1.1
      - libcudf-cu12==25.2.2
      - libcuml-cu12==25.2.1
      - libcuvs-cu12==25.2.1
      - libkvikio-cu12==25.2.1
      - libraft-cu12==25.2.0
      - libucx-cu12==1.18.0
      - libucxx-cu12==0.42.0
      - lightning==2.5.1
      - lightning-utilities==0.14.3
      - llvmlite==0.43.0
      - locket==1.0.0
      - loguru==0.7.3
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - mordred==1.2.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.4.3
      - namex==0.0.8
      - narwhals==1.34.0
      - nest-asyncio==1.6.0
      - networkx==2.8.8
      - numba==0.60.0
      - numba-cuda==0.2.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvcomp-cu12==4.2.0.11
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - nvtx==0.2.11
      - opt-einsum==3.4.0
      - optax==0.2.4
      - optree==0.15.0
      - packaging==24.2
      - pandas==2.2.3
      - partd==1.4.2
      - pillow==11.1.0
      - platformdirs==4.3.7
      - plotly==6.0.1
      - propcache==0.3.1
      - protobuf==5.29.4
      - psutil==7.0.0
      - pyarrow==19.0.1
      - pydeck==0.9.1
      - pygments==2.19.1
      - pylibcudf-cu12==25.2.2
      - pylibraft-cu12==25.2.0
      - pynndescent==0.5.13
      - pynvjitlink-cu12==0.5.2
      - pynvml==12.0.0
      - pyparsing==3.2.3
      - python-levenshtein==0.27.1
      - pytorch-lightning==2.5.1
      - pyyaml==6.0.2
      - raft-dask-cu12==25.2.0
      - rapidfuzz==3.13.0
      - rapids-dask-dependency==25.2.0
      - rdkit==2024.9.6
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.0.0
      - rmm-cu12==25.2.0
      - rpds-py==0.24.0
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - selfies==2.2.0
      - smmap==5.0.2
      - sortedcontainers==2.4.0
      - streamlit==1.44.1
      - sympy==1.13.1
      - tabulate==0.9.0
      - tblib==3.1.0
      - tenacity==9.1.2
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.0.1
      - threadpoolctl==3.6.0
      - tokenizers==0.21.1
      - toml==0.10.2
      - toolz==1.0.0
      - torch==2.6.0
      - torch-geometric==2.6.1
      - torchani==2.2.4
      - torchaudio==2.6.0
      - torchdata==0.11.0
      - torchmetrics==1.7.1
      - torchvision==0.21.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - transformers==4.51.2
      - treelite==4.4.1
      - triton==3.2.0
      - typing-extensions==4.13.1
      - ucx-py-cu12==0.42.0
      - ucxx-cu12==0.42.0
      - umap==0.1.1
      - umap-learn==0.5.7
      - urllib3==2.3.0
      - vadersentiment==3.3.2
      - watchdog==6.0.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - yarl==1.19.0
      - zict==3.0.0
      - zipp==3.21.0
